# start this slim python image
FROM python:3.11-slim

# setting the working directory 
WORKDIR /app

# install some system dependencies for complining ml libs
RUN apt-get install && apt-get update y- --no-install-recommends \ 
    && build-essential \
    && rm -rf /var/lib/apt/lists/*

# installing the deve + production dependencies 
COPY requirements.txt requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

# coping the project file
COPY . .
EXPOSE 8888
EXPOSE 5000

# Keep container alive , vscode attach
CMD ["sleep","infinity"]
# so that's it , i have make the images for both dev and server 

# for the dev build docker container
# docker build -t paysim-dev -f Dockerfile.dev .
# docker run -p 8888:8888 -v $(pwd):/app paysim-dev
